server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:wyc1228/springcloud-config.git #GitHub上面的git仓库名字
          uri: https://github.com/wyc1228/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
          ####读取分支
          force-pull: true #配置为true表示如果本地副本是脏的，将使Spring Cloud Config Server强制从远程存储库拉取配置
          username: wyc1228
          password: wyc199712285415
      label: main
#rabbitmq相关配置 15672是web管理界面的端口，5672是MQ访问的端口
  rabbitmq:
    host: 192.168.127.7
    port: 5672
    username: guest
    password: guest
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'