server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
#            - After=2021-03-20T14:09:02.786+08:00[Asia/Shanghai] # 断言 时间在这个之后可以进行路由
#            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
            - Cookie=username,wyc
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
#            - Host=**.atguigu.com
#            - Method=GET
#            - Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
            # 过滤
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加上一对请求头，名称为x-Request-Id值为1024

        - id: payment_route2 # 路由的id,没有规定规则但要求唯一,建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
#            - Cookie=username,wyc
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
#            - Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由 例如 http://localhost:9527/payment/lb?username=31

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进Eureka服务列表内
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/